services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest 
    restart: no
    ports:
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Secret2025
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data: